version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,dynamodb,events,secretsmanager
      - DEFAULT_REGION=eu-west-1
      - LS_LOG=info
    ports: ["4566:4566"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4566/_localstack/health | grep '\"initialized\": true'"]
      interval: 2s
      timeout: 2s
      retries: 60

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_URL=http://localstack:4566
      - S3_ENDPOINT_URL=http://localstack:4566
      - SQS_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    command: ["/app/scripts/run_tests.sh","integration"]
