# docker-compose.localstack.yml
version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,secretsmanager,iam, dynamodb, logs
      - LS_LOG=info
    ports: ["4566:4566"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      localstack:
        condition: service_started
    command: ["/app/scripts/run_tests.sh","integration"]
